# SPDX-FileCopyrightText: 2020-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: JS Tests
on: pull_request

jobs:
  vitest:
    runs-on: ubuntu-latest

    name: Unit tests

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: versions
        with:
          fallbackNode: '^22'
          fallbackNpm: '^10'

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@${{ steps.versions.outputs.npmVersion }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:unit:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
          flags: javascript
          fail_ci_if_error: ${{ !github.event.pull_request.head.repo.fork }}

  summary:
    runs-on: ubuntu-latest
    needs:
      - vitest

    if: always()

    name: npm-test-summary

    steps:
      - name: Vitest status
        run: if ${{ needs.vitest.result != 'success' && needs.vitest.result != 'skipped' }}; then exit 1; fi
